class Textos:
    titulo_app = "Flet Kanban App"
    login = "Log-in"
    configuraciones = "Configuraciones"
    titulo_appBar = "Kanban"
    fuente_base = "Pacifico"
    encabezado_tablero_demo = "Tablero Demo"
    nuevo_usuario = "Ingrese su Usuario"
    nuevo_password = "Ingrese su contraseña"
    encabezado_nuevo_usuario = "Por favor ingrese su usuario y contraseña/password"
    nuevo_tablero_nombre = "Nombre de Tablero Nuevo"
    nuevo_tablero_boton_crear = "Crear"
    encabezado_dialogo_nuevo_tablero = "Nombra tu nuevo tablero"
    cerrando_modal = "Cerrando Modal"
    boton_cerrar_modal = "Cancelar"
    campo_nuevo_usuario = "Usuario"
    campo_nuevo_password = "Contraseña"
    vista_miembros = "Todos los Miembros"
    vista_tableros = "Todos los Tableros"
    nuevo_tablero_add = "Agregar Nuevo Tablero"
    barra_buscar_tableros = "Buscar todos los Tableros"
    tablero_no_encontrado = "Tablero no encontrado"
    btn_eliminar_tablero = "Eliminar"
    btn_archivar_tablero = "Archivar"

    tarjeta_nueva_nombre = "Nuevo nombre tarjeta"
    btn_guardar_tarjeta = "Guardar"
    pop_menu_editar = "Editar"
    pop_menu_eliminar = "Eliminar"
    pop_menu_mover = "Mover lista"
    agregar_tarjeta = "Agregar Tarjeta"
    
    agregar_item = "Agregar a lista"
    btn_cancelar = "Cancelar"
    btn_crear = "Crear"
    lista_nueva_nombre = "Nombre nueva Lista"
    dialogo_titulo = "Nombra tu nueva lista"
    cerrar_modal = "Modal cerrado."

    nav_rail_tableros = "Tableros"
    nav_rail_miembros = "Miembros"
    sidebar_encabezado = "Espacio de Trabajo"


